{{-- Cláusula: OBJETO DEL CONTRATO. Fuentes: a.1 (base; a.1.2 pluraliza "LOS
     BIENES DESCRITOS"), a.1.6 (custodia: garantía mobiliaria CON POSESIÓN),
     a.1.4/a.1.3 (todos los bienes futuros: PRECONSTITUCIÓN + párrafo de bien
     futuro), a.1.5 (bien futuro y bien presente). Referencias cruzadas via
     $vm->ord->de('bien') / $vm->ord->de('valor'). --}}
@php
    $numsFuturos = [];
    $numsPresentes = [];
    foreach (array_values($vm->bienes) as $i => $b) {
        if (! empty($b['esFuturo'])) {
            $numsFuturos[] = $i + 1;
        } else {
            $numsPresentes[] = $i + 1;
        }
    }
    $plural = count($vm->bienes) > 1;
    $todosFuturos = $numsFuturos !== [] && $numsPresentes === [];
    $mixto = $numsFuturos !== [] && $numsPresentes !== [];
    // 'VEHICULO 1' / 'VEHICULOS 1 Y 2' (para el caso mixto, según a.1.5)
    $comoVehiculo = fn (array $nums) => (count($nums) > 1 ? 'VEHICULOS ' : 'VEHICULO ').implode(' Y ', $nums);
@endphp
<div class="clausula">
    <div class="clausula-titulo">{{ $vm->ord->de('objeto') }}: OBJETO DEL CONTRATO</div>

    @if ($vm->custodia)
        <p class="parrafo">EL PRESENTE CONTRATO TIENE POR OBJETO LA CONSTITUCIÓN DE UNA GARANTÍA MOBILIARIA CON POSESIÓN SOBRE {{ $plural ? 'LOS VEHÍCULOS DESCRITOS' : 'EL VEHÍCULO DESCRITO' }} EN LA CLÁUSULA {{ $vm->ord->de('bien') }}, EL CUAL ES ENTREGADO EN ESTE MISMO ACTO POR {{ $vm->g->deudor() }} A EL ACREEDOR EN CALIDAD DE DEPOSITARIO PARA SU CUSTODIA Y CONSERVACIÓN, DE CONFORMIDAD CON LO DISPUESTO EN EL DECRETO LEGISLATIVO N.° 1400 Y SU INSCRIPCIÓN EN EL SISTEMA INFORMATIVO DE GARANTÍAS MOBILIARIAS -SIGM ADMINISTRADO POR LA SUNARP, CON LA FINALIDAD DE GARANTIZAR EL CUMPLIMIENTO ÍNTEGRO Y OPORTUNO DE LA OBLIGACIÓN ESTABLECIDA EN LA CLÁUSULA {{ $vm->ord->de('valor') }} DEL PRESENTE CONTRATO, INCLUYENDO CAPITAL, INTERESES COMPENSATORIOS Y MORATORIOS, PENALIDADES, GASTOS ADMINISTRATIVOS, GASTOS DE CUSTODIA, CONSERVACIÓN, EJECUCIÓN Y CUALQUIER OTRO CONCEPTO DERIVADO DE LA RELACIÓN CONTRACTUAL. ASIMISMO, {{ $vm->g->deudor() }} {{ $vm->g->verbo('MANIFIESTA', 'MANIFIESTAN') }} DE MANERA EXPRESA E IRREVOCABLE SU VOLUNTAD DE CONSTITUIR LA PRESENTE GARANTÍA MOBILIARIA CON POSESIÓN A FAVOR DE EL ACREEDOR, ACEPTANDO EN TODOS SUS EXTREMOS LAS CONDICIONES Y ESTIPULACIONES CONTENIDAS EN EL PRESENTE CONTRATO.</p>
    @elseif ($todosFuturos)
        <p class="parrafo">EL PRESENTE CONTRATO TIENE POR OBJETO LA PRECONSTITUCIÓN DE UNA GARANTÍA MOBILIARIA SOBRE {{ $plural ? 'LOS BIENES FUTUROS DESCRITOS' : 'UN BIEN FUTURO DESCRITO' }} EN LA CLÁUSULA {{ $vm->ord->de('bien') }}, EN FAVOR DE EL ACREEDOR, CONFORME AL NUEVO SISTEMA DE GARANTÍAS MOBILIARIAS DE LA SUNARP EN EL MARCO DEL DECRETO LEGISLATIVO N.º 1400, A FIN DE GARANTIZAR EL CUMPLIMIENTO DE LA OBLIGACIÓN ESTABLECIDA EN LA CLÁUSULA {{ $vm->ord->de('valor') }}.</p>
        <p class="parrafo">LA GARANTÍA MOBILIARIA CONSTITUIDA RECAE SOBRE {{ $plural ? 'LOS BIENES FUTUROS' : 'UN BIEN FUTURO' }}, EN LOS TÉRMINOS PREVISTOS EN EL DECRETO LEGISLATIVO N° 1400, TODA VEZ QUE, AL MOMENTO DE LA CELEBRACIÓN DEL PRESENTE CONTRATO, {{ $plural ? 'LOS VEHICULOS DETALLADOS' : 'EL VEHÍCULO DETALLADO' }} EN LA CLÁUSULA {{ $vm->ord->de('bien') }} AÚN NO {{ $plural ? 'FIGURAN INSCRITOS' : 'FIGURA INSCRITO' }} A NOMBRE DE {{ $vm->g->deudor() }} EN LOS REGISTROS PÚBLICOS – SUNARP. NO OBSTANTE, SE HA OTORGADO EL IMPORTE TOTAL DEL PRÉSTAMO CONFORME AL MONTO DE LA OBLIGACION PRINCIPAL, PRE-CONSTITUYÉNDOSE ASÍ VÁLIDAMENTE LA GARANTÍA SOBRE {{ $plural ? 'LOS BIENES FUTUROS' : 'EL BIEN FUTURO' }} CUYA ADQUISICIÓN A NOMBRE DE {{ $vm->g->deudor() }} ESTA EN PROCESO.</p>
    @elseif ($mixto)
        <p class="parrafo">EL PRESENTE CONTRATO TIENE POR OBJETO LA PRECONSTITUCIÓN DE UNA GARANTÍA MOBILIARIA SOBRE {{ count($numsFuturos) > 1 ? 'LOS BIENES FUTUROS DESCRITOS' : 'UN BIEN FUTURO DESCRITO' }} EN LA CLÁUSULA {{ $vm->ord->de('bien') }} COMO {{ $comoVehiculo($numsFuturos) }}, Y LA CONSTITUCIÓN DE UNA GARANTÍA MOBILIARIA SOBRE {{ count($numsPresentes) > 1 ? 'LOS BIENES PRESENTES DESCRITOS' : 'UN BIEN PRESENTE DESCRITO' }} EN LA CLÁUSULA {{ $vm->ord->de('bien') }} COMO {{ $comoVehiculo($numsPresentes) }}; EN FAVOR DE EL ACREEDOR, CONFORME AL NUEVO SISTEMA DE GARANTÍAS MOBILIARIAS DE LA SUNARP EN EL MARCO DEL DECRETO LEGISLATIVO N.º 1400, A FIN DE GARANTIZAR EL CUMPLIMIENTO DE LA OBLIGACIÓN ESTABLECIDA EN LA CLÁUSULA {{ $vm->ord->de('valor') }}.</p>
        <p class="parrafo">LA GARANTÍA MOBILIARIA PRE-CONSTITUIDA RECAE SOBRE {{ count($numsFuturos) > 1 ? 'LOS BIENES FUTUROS' : 'UN BIEN FUTURO' }}, EN LOS TÉRMINOS PREVISTOS EN EL DECRETO LEGISLATIVO N° 1400, TODA VEZ QUE, AL MOMENTO DE LA CELEBRACIÓN DEL PRESENTE CONTRATO, EL {{ $comoVehiculo($numsFuturos) }} {{ count($numsFuturos) > 1 ? 'DETALLADOS' : 'DETALLADO' }} EN LA CLÁUSULA {{ $vm->ord->de('bien') }} AÚN NO {{ count($numsFuturos) > 1 ? 'FIGURAN INSCRITOS' : 'FIGURA INSCRITO' }} A NOMBRE DE {{ $vm->g->deudor() }} EN LOS REGISTROS PÚBLICOS – SUNARP. NO OBSTANTE, SE HA OTORGADO EL IMPORTE TOTAL DEL PRÉSTAMO CONFORME AL MONTO DE LA OBLIGACION PRINCIPAL, PRE-CONSTITUYÉNDOSE ASÍ VÁLIDAMENTE LA GARANTÍA SOBRE EL BIEN FUTURO CUYA ADQUISICIÓN A NOMBRE DE {{ $vm->g->deudor() }} ESTA EN PROCESO. ASIMISMO, {{ $vm->g->deudor() }} {{ $vm->g->verbo('MANIFIESTA', 'MANIFIESTAN') }} DE MANERA EXPRESA SU VOLUNTAD DE PRE-CONSTITUIR EL {{ $comoVehiculo($numsFuturos) }} Y CONSTITUIR EL {{ $comoVehiculo($numsPresentes) }} EN LA PRESENTE GARANTÍA MOBILIARIA EN FAVOR DE EL ACREEDOR, ACEPTANDO TODAS LAS CONDICIONES ESTABLECIDAS EN EL PRESENTE CONTRATO.</p>
    @else
        <p class="parrafo">EL PRESENTE CONTRATO TIENE POR OBJETO LA CONSTITUCIÓN DE UNA GARANTÍA MOBILIARIA SOBRE {{ $plural ? 'LOS BIENES DESCRITOS' : 'EL BIEN DESCRITO' }} EN LA CLÁUSULA {{ $vm->ord->de('bien') }}, EN FAVOR DE EL ACREEDOR, CONFORME AL SISTEMA INFORMATIVO DE GARANTÍAS MOBILIARIAS DE LA SUNARP EN EL MARCO DEL DECRETO LEGISLATIVO N.º 1400, A FIN DE GARANTIZAR EL CUMPLIMIENTO DE LA OBLIGACIÓN ESTABLECIDA EN LA CLÁUSULA {{ $vm->ord->de('valor') }}. ASIMISMO, {{ $vm->g->deudor() }} {{ $vm->g->verbo('MANIFIESTA', 'MANIFIESTAN') }} DE MANERA EXPRESA SU VOLUNTAD DE CONSTITUIR LA PRESENTE GARANTÍA MOBILIARIA EN FAVOR DE EL ACREEDOR, ACEPTANDO TODAS LAS CONDICIONES ESTABLECIDAS EN EL PRESENTE CONTRATO.</p>
    @endif
</div>
