{{-- CLÁUSULA: PROHIBICIÓN, con sus 6 numerales internos. La numeración interna
     es DINÁMICA ($vm->ord->numero('prohibicion')): en los contratos con GPS la
     cláusula es la 17 (17.1–17.6) y en los b.* cae a la 16 (16.1–16.6). --}}
@php($n = $vm->ord->numero('prohibicion'))
<div class="clausula">
    <div class="clausula-titulo">{{ $vm->ord->de('prohibicion') }}: PROHIBICIÓN</div>

    <div class="subtitulo">{{ $n }}.1. PROHIBICIÓN DE DISPOSICIÓN</div>
    <p class="parrafo">LAS PARTES ACUERDAN QUE {{ $vm->g->deudor() }} {{ $vm->g->verbo('QUEDA', 'QUEDAN') }} EXPRESAMENTE {{ $vm->g->flex('PROHIBIDO') }} DE VENDER, DONAR, PERMUTAR, CEDER, TRANSFERIR, GRAVAR O REALIZAR CUALQUIER OTRO ACTO JURÍDICO, ONEROSO O GRATUITO, RESPECTO DEL VEHÍCULO DADO EN GARANTÍA, SALVO AUTORIZACIÓN PREVIA, EXPRESA Y ESCRITA DE EL ACREEDOR. LA PRESENTE RESTRICCIÓN CONSTITUYE PACTO EN CONTRARIO CONFORME AL ARTÍCULO 46 DEL DECRETO LEGISLATIVO N.° 1400 Y SE MANTENDRÁ VIGENTE HASTA LA CANCELACIÓN DE LA GARANTÍA MOBILIARIA EN EL SIGM.</p>

    <div class="subtitulo">{{ $n }}.2. INCUMPLIMIENTO GRAVE Y VENCIMIENTO ANTICIPADO</div>
    <p class="parrafo">LA TRANSFERENCIA, GRAVAMEN, OCULTAMIENTO O DISPOSICIÓN NO AUTORIZADA DEL VEHÍCULO, ASÍ COMO CUALQUIER ACTO DESTINADO A DIFICULTAR SU UBICACIÓN, CONSERVACIÓN, RECUPERACIÓN O EJECUCIÓN, CONSTITUIRÁ INCUMPLIMIENTO GRAVE DEL CONTRATO Y FACULTARÁ A EL ACREEDOR A DECLARAR EL VENCIMIENTO ANTICIPADO DE TODAS LAS OBLIGACIONES PENDIENTES, EXIGIR EL PAGO INMEDIATO DEL SALDO DEUDOR E INICIAR LA EJECUCIÓN JUDICIAL O EXTRAJUDICIAL DE LA GARANTÍA MOBILIARIA, SIN NECESIDAD DE ESPERAR LA ACUMULACIÓN DE TRES (03) CUOTAS IMPAGAS.</p>

    <div class="subtitulo">{{ $n }}.3. GASTOS GENERADOS POR EL INCUMPLIMIENTO</div>
    <p class="parrafo">TODOS LOS GASTOS RAZONABLES, NECESARIOS Y DEBIDAMENTE SUSTENTADOS QUE SE GENEREN COMO CONSECUENCIA DIRECTA DEL INCUMPLIMIENTO DE LA PRESENTE CLÁUSULA SERÁN ASUMIDOS POR {{ $vm->g->deudor() }}, INCLUYENDO GASTOS NOTARIALES, REGISTRALES, ADMINISTRATIVOS, DE VERIFICACIÓN, LOCALIZACIÓN, RECUPERACIÓN, TRASLADO, CUSTODIA Y EJECUCIÓN DEL VEHÍCULO, ASÍ COMO LOS COSTOS Y COSTAS JUDICIALES QUE LEGALMENTE CORRESPONDAN, SIN PERJUICIO DE LOS INTERESES MORATORIOS Y DEMÁS CONCEPTOS PACTADOS EN EL PRESENTE CONTRATO.</p>

    <div class="subtitulo">{{ $n }}.4. SUBSISTENCIA Y PERSECUCIÓN DE LA GARANTÍA</div>
    <p class="parrafo">LA TRANSFERENCIA NO AUTORIZADA DEL VEHÍCULO NO EXTINGUE, LIBERA NI CANCELA LA GARANTÍA MOBILIARIA, CONSERVANDO EL ACREEDOR EL DERECHO DE PERSEGUIR Y EJECUTAR EL BIEN AUN CUANDO HAYA SIDO TRANSFERIDO A TERCEROS, EN LOS SUPUESTOS Y CON LAS EXCEPCIONES PREVISTAS EN EL DECRETO LEGISLATIVO N.° 1400.</p>

    <div class="subtitulo">{{ $n }}.5. ADVERTENCIA SOBRE EVENTUAL RESPONSABILIDAD PENAL</div>
    <p class="parrafo">{{ $vm->g->deudor() }} {{ $vm->g->verbo('DECLARA', 'DECLARAN') }} CONOCER QUE LA VENTA O EL GRAVAMEN DEL VEHÍCULO COMO SI ESTUVIERA LIBRE, PESE A ENCONTRARSE AFECTO A UNA GARANTÍA MOBILIARIA VIGENTE, PODRÁ SER PUESTA EN CONOCIMIENTO DEL MINISTERIO PÚBLICO PARA QUE, DE CORRESPONDER Y SI CONCURREN LOS ELEMENTOS EXIGIDOS POR LA LEY, SE EVALÚE LA EVENTUAL COMISIÓN DEL DELITO DE DEFRAUDACIÓN PREVISTO EN EL ARTÍCULO 197, NUMERAL 4, DEL CÓDIGO PENAL, SIN PERJUICIO DE LAS DEMÁS RESPONSABILIDADES CIVILES O PENALES QUE PUDIERAN CORRESPONDER.</p>

    <div class="subtitulo">{{ $n }}.6. NO CONVALIDACIÓN DEL INCUMPLIMIENTO</div>
    <p class="parrafo">LA RECEPCIÓN POR PARTE DE EL ACREEDOR DE CUOTAS, PAGOS PARCIALES, INTERESES O CUALQUIER OTRA SUMA CON POSTERIORIDAD AL INCUMPLIMIENTO DE LA PRESENTE CLÁUSULA NO IMPLICARÁ AUTORIZACIÓN, CONVALIDACIÓN, NOVACIÓN NI RENUNCIA AL VENCIMIENTO ANTICIPADO O A LA EJECUCIÓN DE LA GARANTÍA MOBILIARIA, SALVO DECLARACIÓN EXPRESA Y ESCRITA DE EL ACREEDOR.</p>
</div>
