{{-- Encabezado del contrato: título (.titulo-contrato) + párrafo introductorio.
     Fuente: modelo a.1 (título y "CONSTE POR EL PRESENTE DOCUMENTO...");
     con $vm->custodia se usa el título/redacción de a.1.6 ("CON POSESIÓN");
     si todos los bienes son futuros, el de a.1.4 ("PRE-CONSTITUCIÓN");
     si hay bien futuro y presente, el de a.1.5. --}}
@php
    $encFuturos = array_filter($vm->bienes, fn ($b) => ! empty($b['esFuturo']));
    $encTodosFuturos = count($encFuturos) > 0 && count($encFuturos) === count($vm->bienes);
    $encMixto = count($encFuturos) > 0 && ! $encTodosFuturos;
@endphp
@if ($vm->custodia)
    <div class="titulo-contrato">CONTRATO DE CRÉDITO VEHICULAR CON CONSTITUCIÓN DE GARANTÍA MOBILIARIA CON POSESIÓN EN EL SISTEMA INFORMATIVO DE GARANTÍAS MOBILIARIAS – SIGM</div>
    <p class="parrafo">CONSTE POR EL PRESENTE DOCUMENTO EL CONTRATO DE CONSTITUCIÓN DE GARANTÍA MOBILIARIA CON POSESIÓN MEDIANTE EL SISTEMA INFORMATIVO DE GARANTIAS MOBILIARIAS - SIGM, QUE CELEBRAN DE UNA PARTE:</p>
@elseif ($encTodosFuturos)
    <div class="titulo-contrato">CONTRATO DE CRÉDITO VEHICULAR CON PRE-CONSTITUCIÓN DE GARANTÍA MOBILIARIA EN EL SISTEMA INFORMATIVO DE GARANTÍAS MOBILIARIAS – SIGM</div>
    <p class="parrafo">CONSTE POR EL PRESENTE DOCUMENTO EL CONTRATO DE PRE-CONSTITUCIÓN DE GARANTÍA MOBILIARIA MEDIANTE EL SISTEMA INFORMATIVO DE GARANTIAS MOBILIARIAS - SIGM, QUE CELEBRAN DE UNA PARTE:</p>
@elseif ($encMixto)
    <div class="titulo-contrato">CONTRATO DE CRÉDITO VEHICULAR CON CONSTITUCIÓN DE GARANTÍA MOBILIARIA SOBRE BIEN FUTURO Y BIEN PRESENTE EN EL SISTEMA INFORMATIVO DE GARANTÍAS MOBILIARIAS – SIGM</div>
    <p class="parrafo">CONSTE POR EL PRESENTE DOCUMENTO EL CONTRATO DE CONSTITUCIÓN DE GARANTÍA MOBILIARIA SOBRE BIEN FUTURO Y BIEN PRESENTE MEDIANTE EL SISTEMA INFORMATIVO DE GARANTIAS MOBILIARIAS - SIGM, QUE CELEBRAN DE UNA PARTE:</p>
@else
    <div class="titulo-contrato">CONTRATO DE CRÉDITO VEHICULAR CON CONSTITUCIÓN DE GARANTÍA MOBILIARIA EN EL SISTEMA INFORMATIVO DE GARANTÍAS MOBILIARIAS – SIGM</div>
    <p class="parrafo">CONSTE POR EL PRESENTE DOCUMENTO EL CONTRATO DE CONSTITUCIÓN DE GARANTÍA MOBILIARIA MEDIANTE EL SISTEMA INFORMATIVO DE GARANTIAS MOBILIARIAS - SIGM, QUE CELEBRAN DE UNA PARTE:</p>
@endif
