{{-- Cláusula: DESCRIPCIÓN DE LA OBLIGACIÓN GARANTIZADA. Fuente: a.1, verbatim;
     con $vm->custodia se insertan los "CON POSESIÓN" de a.1.6. La fecha de los
     anexos 1 y 2 es $vm->fechaSimple. --}}
@php($conPosesion = $vm->custodia ? ' CON POSESIÓN' : '')
<div class="clausula">
    <div class="clausula-titulo">{{ $vm->ord->de('obligacion') }}: DESCRIPCIÓN DE LA OBLIGACIÓN GARANTIZADA</div>
    <p class="parrafo">LA PRESENTE GARANTÍA MOBILIARIA{{ $conPosesion }} TIENE POR OBJETO GARANTIZAR EL CRÉDITO VEHICULAR Y LAS DEMÁS OBLIGACIONES DERIVADAS DE LA OBLIGACIÓN PRINCIPAL, CONFORME A LO ESTABLECIDO EN EL DECRETO LEGISLATIVO N.º 1400. ASIMISMO, AMBAS PARTES MANIFIESTAN EXPRESAMENTE SU VOLUNTAD DE CONSTITUIR LA PRESENTE GARANTÍA MOBILIARIA{{ $conPosesion }}, DEJANDO CONSTANCIA QUE {{ $vm->g->deudor() }} {{ $vm->g->verbo('AUTORIZA', 'AUTORIZAN') }} DE MANERA EXPRESA A EL ACREEDOR PARA EFECTUAR POSTERIORMENTE LA CONSTITUCIÓN DE LA GARANTÍA MOBILIARIA EN EL SISTEMA INFORMATIVO DE GARANTÍAS MOBILIARIAS (SIGM), UNA VEZ SUSCRITO EL PRESENTE ACTO JURÍDICO CONSTITUTIVO. ADEMÁS, EL PRESENTE CONTRATO, JUNTO CON LOS ANEXOS 1 Y 2, DE FECHA {{ $vm->fechaSimple }}, FORMAN PARTE DEL ACTO DE CONSTITUCIÓN DE LA GARANTÍA MOBILIARIA{{ $conPosesion }} Y ACREDITA LA MANIFESTACIÓN DE VOLUNTAD Y AUTORIZACIÓN NECESARIA PARA SU INSCRIPCIÓN EN EL SISTEMA INFORMATIVO DE GARANTIAS MOBILIARIAS - SIGM.</p>
</div>
