{{-- Cláusula: DESCRIPCIÓN DE LA OBLIGACIÓN GARANTIZADA. Fuente: a.1, verbatim;
     con $vm->custodia se insertan los "CON POSESIÓN" de a.1.6. La fecha de los
     anexos 1 y 2 es $vm->fechaSimple.

     El párrafo del cambio de condición (bien futuro → bien presente en el
     SIGM) es EXCLUSIVO del caso mixto (a.1.5/a.2.5/a.3.5): verificado que
     a.1.3 (dos futuros) NO lo trae — no se generaliza. En el mixto, el
     vehículo 1 es siempre el futuro (ModelosContrato::SLOTS_BIENES). --}}
@php
    $conPosesion = $vm->custodia ? ' CON POSESIÓN' : '';
    $oblFuturos = array_filter($vm->bienes, fn ($b) => ! empty($b['esFuturo']));
    $oblMixto = $oblFuturos !== [] && count($oblFuturos) < count($vm->bienes);
@endphp
<div class="clausula">
    <div class="clausula-titulo">{{ $vm->ord->de('obligacion') }}: DESCRIPCIÓN DE LA OBLIGACIÓN GARANTIZADA</div>
    <p class="parrafo">LA PRESENTE GARANTÍA MOBILIARIA{{ $conPosesion }} TIENE POR OBJETO GARANTIZAR EL CRÉDITO VEHICULAR Y LAS DEMÁS OBLIGACIONES DERIVADAS DE LA OBLIGACIÓN PRINCIPAL, CONFORME A LO ESTABLECIDO EN EL DECRETO LEGISLATIVO N.º 1400. ASIMISMO, AMBAS PARTES MANIFIESTAN EXPRESAMENTE SU VOLUNTAD DE CONSTITUIR LA PRESENTE GARANTÍA MOBILIARIA{{ $conPosesion }}, DEJANDO CONSTANCIA QUE {{ $vm->g->deudor() }} {{ $vm->g->verbo('AUTORIZA', 'AUTORIZAN') }} DE MANERA EXPRESA A EL ACREEDOR PARA EFECTUAR POSTERIORMENTE LA CONSTITUCIÓN DE LA GARANTÍA MOBILIARIA EN EL SISTEMA INFORMATIVO DE GARANTÍAS MOBILIARIAS (SIGM), UNA VEZ SUSCRITO EL PRESENTE ACTO JURÍDICO CONSTITUTIVO. ADEMÁS, EL PRESENTE CONTRATO, JUNTO CON LOS ANEXOS 1 Y 2, DE FECHA {{ $vm->fechaSimple }}, FORMAN PARTE DEL ACTO DE CONSTITUCIÓN DE LA GARANTÍA MOBILIARIA{{ $conPosesion }} Y ACREDITA LA MANIFESTACIÓN DE VOLUNTAD Y AUTORIZACIÓN NECESARIA PARA SU INSCRIPCIÓN EN EL SISTEMA INFORMATIVO DE GARANTIAS MOBILIARIAS - SIGM.</p>

    @if ($oblMixto)
        <p class="parrafo">ADEMÁS, RESPECTO DEL VEHÍCULO 1 CUYA GARANTÍA SE CONSTITUYE EN CALIDAD DE BIEN FUTURO, POR ENCONTRARSE EN PROCESO DE TRANSFERENCIA DE PROPIEDAD A FAVOR DE {{ $vm->g->deudor() }}, ESTE {{ $vm->g->verbo('AUTORIZA', 'AUTORIZAN') }} DE MANERA EXPRESA E IRREVOCABLE A EL ACREEDOR PARA QUE, UNA VEZ ACREDITADA LA INSCRIPCIÓN REGISTRAL DEL VEHÍCULO A SU NOMBRE, PUEDA MODIFICAR EN EL SISTEMA INFORMATIVO DE GARANTÍAS MOBILIARIAS (SIGM) LA CONDICIÓN DE LA GARANTÍA, PASANDO DE BIEN FUTURO A BIEN PRESENTE, ASÍ COMO EFECTUAR LAS ACTUALIZACIONES, PRECISIONES O MODIFICACIONES QUE RESULTEN NECESARIAS PARA MANTENER LA PLENA VIGENCIA, OPONIBILIDAD Y EFICACIA DE LA GARANTÍA MOBILIARIA, SIN QUE SEA NECESARIA LA SUSCRIPCIÓN DE UN NUEVO CONTRATO, ADENDA O AUTORIZACIÓN ADICIONAL, POR CONSTITUIR DICHA MODIFICACIÓN UNA ADECUACIÓN DE LA INFORMACIÓN REGISTRAL Y NO UNA NUEVA CONSTITUCIÓN DE GARANTÍA.</p>
    @endif
</div>
