{{-- Cláusula: REPRESENTANTES PARA LA EJECUCIÓN. Fuente: modelo a.1 (DÉCIMO),
     verbatim. Los representantes salen de la constante
     'representantes_ejecucion' (lista de nombre/dni/domicilio). --}}
<div class="clausula">
    <div class="clausula-titulo">{{ $vm->ord->de('representantes') }}: REPRESENTANTES PARA LA EJECUCIÓN</div>
    <p class="parrafo">LAS PARTES, {{ $vm->g->deudor() }} Y EL ACREEDOR, ACUERDAN DESIGNAR COMO REPRESENTANTES PARA TODOS LOS EFECTOS PREVISTOS EN EL PRESENTE CONTRATO Y EN LA LEY, CON FACULTADES AMPLIAS, SUFICIENTES E IRREVOCABLES, PARA EJECUTAR LA VENTA EXTRAJUDICIAL O LA ADJUDICACIÓN DIRECTA DE LA GARANTÍA MOBILIARIA, A SOLA FIRMA Y DE MANERA INDISTINTA, CONFORME A LO ESTIPULADO EN EL PRESENTE ACTO JURÍDICO CONSTITUTIVO, A LAS SIGUIENTES PERSONAS:</p>
    @foreach ($vm->constante('representantes_ejecucion', []) as $representante)
        <p class="parrafo">{{ mb_strtoupper($representante['nombre']) }}, IDENTIFICADO CON DNI N.° {{ $representante['dni'] }}, CON DOMICILIO EN {{ mb_strtoupper($representante['domicilio']) }}.</p>
    @endforeach
    <p class="parrafo">CUALQUIERA DE LOS REPRESENTANTES ANTES MENCIONADOS SE ENCUENTRA PLENAMENTE AUTORIZADO POR {{ $vm->g->deudor() }} Y EL ACREEDOR PARA EJERCER, DE MANERA INDIVIDUAL E INDISTINTA, TODAS LAS FACULTADES OTORGADAS EN EL PRESENTE CONTRATO, INCLUYENDO, SIN CARÁCTER LIMITATIVO, LA EJECUCIÓN DE LA GARANTÍA MOBILIARIA, LA TOMA DE POSESIÓN DEL BIEN, SU EXHIBICIÓN, VENTA, ADJUDICACIÓN, SUSCRIPCIÓN DE DOCUMENTOS, ACTAS, CONSTANCIAS, RECIBOS Y DEMÁS INSTRUMENTOS NECESARIOS PARA EL CUMPLIMIENTO DEL PRESENTE ACTO JURÍDICO, CONFORME A LO ESTIPULADO EN EL PRESENTE ACTO JURÍDICO CONSTITUTIVO. LAS PARTES DEJAN CONSTANCIA DE QUE LAS FACULTADES CONFERIDAS MANTIENEN SU VIGENCIA HASTA LA TOTAL EXTINCIÓN DE LAS OBLIGACIONES GARANTIZADAS.</p>
</div>
