{{-- CLÁUSULA: APLICACIÓN SUPLETORIA DE LA LEY. Texto verbatim de la plantilla
     maestra (a.1 GPS. Deudor); no lleva datos variables. --}}
<div class="clausula">
    <div class="clausula-titulo">{{ $vm->ord->de('supletoria') }}: APLICACIÓN SUPLETORIA DE LA LEY</div>
    <p class="parrafo">EN TODO LO NO PREVISTO POR LAS PARTES EN EL PRESENTE CONTRATO, AMBAS SE SOMETEN A LO ESTABLECIDO POR LAS NORMAS DEL CÓDIGO CIVIL, CÓDIGO PROCESAL CIVIL Y DEMÁS DEL SISTEMA JURÍDICO PERUANO QUE RESULTEN APLICABLES. ASIMISMO, TODAS LAS CONTROVERSIAS QUE SE SUSCRIBEN ENTRE LAS PARTES COMO CONSECUENCIA DE INCUMPLIMIENTO DE LA EJECUCIÓN DEL CONTRATO, QUE NO SE SOLUCIONEN DE COMÚN ACUERDO, QUEDAN SOMETIDAS ANTE CUALQUIER ÓRGANO JURISDICCIONAL DENTRO DEL TERRITORIO NACIONAL, INCLUIDO DE LOS DOMICILIOS QUE RENUNCIAN CONFORME LA PRÓRROGA CONVENCIONAL DE LA COMPETENCIA TERRITORIAL DE ACUERDO A LO ESTABLECIDO EN EL ARTÍCULO 25º DEL CÓDIGO PROCESAL CIVIL.</p>
</div>
